scraper:
  articles:
    connect-timeout-seconds: '30'
    task-interval-seconds: '60'
    websites:
      - url: https://www.idnes.cz/
        website-type: idnes
      - url: https://ihned.cz/
        website-type: hn
      - url: https://www.bbc.com/
        website-type: bbc
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
        search:
          backend:
            directory:
              root: ./index/lucene
    hibernate:
      ddl-auto: update
    show-sql: 'false'
  datasource:
    url: jdbc:postgresql://localhost:5432/articles
    username: postgres
    password: admin
logging:
  file:
    name: webscraper.log
springdoc:
  swagger-ui:
    path: swagger-ui
